version: '3.8'

services:
  postgres:
    image: postgres:14-alpine3.20
    container_name: postgres-invest
    environment:
      POSTGRES_DB: invest
      POSTGRES_USER: invest_user
      POSTGRES_PASSWORD: invest_password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata: